version: "3.3"

services:
  crawler:
    container_name: social-scanner-crawler
    build:
      context: ./
      dockerfile: ./Dockerfile
    working_dir: /crawler
    restart: unless-stopped
    tty: true
    volumes:
      - .:/crawler
    networks:
      - social-scanner-network
    ports:
      - 9300:${PORT}
    environment:
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}

networks:
  social-scanner-network:

