from sqlalchemy import Column, Integer, String, Boolean, Float, DateTime, JSON
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.sql import func

Base = declarative_base()

class Product(Base):
    __tablename__ = 'products'

    id = Column(Integer, primary_key=True)
    item_id = Column(String, unique=True)
    shop_id = Column(String)
    name = Column(String)
    catid = Column(Integer)
    stock = Column(Integer)
    status = Column(Integer)
    ctime = Column(Integer)
    t_ctime = Column(String)
    sold = Column(Integer)
    historical_sold = Column(Integer)
    liked_count = Column(Integer)
    brand = Column(String)
    cmt_count = Column(Integer)
    item_status = Column(String)
    price = Column(Integer)
    price_min = Column(Integer)
    price_max = Column(Integer)
    price_before_discount = Column(Integer)
    show_discount = Column(Integer)
    raw_discount = Column(Integer)
    tier_variations_option = Column(String)
    rating_star_avg = Column(Float)
    rating_star_1 = Column(Integer)
    rating_star_2 = Column(Integer)
    rating_star_3 = Column(Integer)
    rating_star_4 = Column(Integer)
    rating_star_5 = Column(Integer)
    item_type = Column(Integer)
    is_adult = Column(Boolean)
    has_lowest_price_guarantee = Column(Boolean)
    is_official_shop = Column(Boolean)
    is_cc_installment_payment_eligible = Column(Boolean)
    is_non_cc_installment_payment_eligible = Column(Boolean)
    is_preferred_plus_seller = Column(Boolean)
    is_mart = Column(Boolean)
    is_service_by_shopee = Column(Boolean)
    shopee_verified = Column(Boolean)
    show_shopee_verified_label = Column(Boolean)
    show_official_shop_label_in_title = Column(Boolean)
    show_free_shipping = Column(Boolean)
    insert_date = Column(String)
    local_categories = Column(JSON)
    global_categories = Column(JSON)
    shop_location = Column(String)
    image = Column(String)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
